#!/usr/bin/with-contenv bash

echo '
*******************************************************
*******************************************************
*                                                     *
*                                                     *
*          This image has been deprecated             *
*                                                     *
*           Use the multi-arch images at              *
*                                                     *
*               linuxserver/transmission              *
*                                                     *
*    https://hub.docker.com/r/linuxserver/transmission*
*                                                     *
*   https://github.com/linuxserver/docker-transmission*
*                                                     *
*                                                     *
*                                                     *
*******************************************************
*******************************************************'
